mehta-lab/recOrder

- examples/example_configs/config_example_qlipp.yml
- recOrder/io/zarr_converter.py
- recOrder/tests/config_reader_tests/test_config_reader.py
- recOrder/tests/conftest.py
- recOrder/tests/converter_tests/test_converter.py
- recOrder/tests/pipeline_tests/test_fluorescence_deconvolution_pipeline.py
- recOrder/tests/pipeline_tests/test_phase_from_bf_pipeline.py
- recOrder/tests/pipeline_tests/test_pre_post_processing.py
- recOrder/tests/pipeline_tests/test_qlipp_pipeline.py
- recOrder/tests/pipeline_tests/test_qlipp_pipeline_tiff.py
- recOrder/tests/reader_tests/test_reader.py
- recOrder/tests/test_configs/config_postprocessing_pytest.yml
- recOrder/tests/test_configs/config_preprocessing_pytest.yml
- recOrder/tests/test_configs/fluor_deconv/config_fluor_2D_pytest.yml
- recOrder/tests/test_configs/phase/config_phase_2D_pytest.yml
- recOrder/tests/test_configs/phase/config_phase_3D_pytest.yml
- recOrder/tests/test_configs/phase/config_phase_full_pytest.yml
- recOrder/tests/test_configs/qlipp/config_qlipp_2D_pytest.yml
- recOrder/tests/test_configs/qlipp/config_qlipp_2D_pytest_tiff.yml
- recOrder/tests/test_configs/qlipp/config_qlipp_full_pytest.yml
- recOrder/tests/test_configs/qlipp/config_qlipp_full_pytest_tiff.yml
- recOrder/tests/test_configs/qlipp/config_qlipp_full_recon_pytest.yml
- recOrder/tests/test_configs/qlipp/config_qlipp_full_recon_pytest_tiff.yml
> Restructure tests

- recOrder/plugin/widget/main_widget.py
- recOrder/plugin/workers/calibration_workers.py
This commit is cherry picked from #160 to narrow it's scope. 
Context from that thread @ieivanov:
> Don't update calibration metadata

- docs/microscope-installation-guide.md
- recOrder/plugin/widget/main_widget.py
- setup.cfg
This PR upgrades:
`pycromanager == 0.13.2 --> 0.19.2`
`micromanager == 20210713 --> 20220901`.
> Upgrade `pycromanager` and `micromanager` 

- recOrder/plugin/widget/main_widget.py
> Remove pre-acquisition background file check for 'Estimated' background correction

- recOrder/plugin/widget/main_widget.py
- recOrder/plugin/workers/calibration_workers.py
> Add "pad_z" when constructing microscope metadata

- recOrder/plugin/workers/calibration_workers.py
> Save background reconstruction and visualization

- recOrder/calib/Calibration.py
- recOrder/io/core_functions.py
- recOrder/plugin/widget/main_widget.py
- recOrder/plugin/workers/calibration_workers.py
> Fix 'Capture Background' when MM is in 'Live' mode

- .github/workflows/plugin_preview.yml
> Bump napari-hub-preview-action version to fix CI

- recOrder/plugin/main_widget.py
> Override initial tab to focus on 'LC Calibration'

- recOrder/plugin/main_widget.py
> Use HSV colormap for the background orientation layer

- recOrder/plugin/main_widget.py
> Draw overlay for both 2D and 3D birefringence acquisitions

- recOrder/acq/acquisition_workers.py
- recOrder/calib/calibration_workers.py
- recOrder/plugin/main_widget.py
> Read illumination parameters from the loaded calibration instead of GUI during acquisition

- recOrder/acq/acquisition_workers.py
- recOrder/plugin/main_widget.py
> Add ROI size check for the previous phase reconstructor

- setup.cfg
Remove unnecessary dependencies.
> Dependency cleanup

- recOrder/acq/acq_functions.py
- recOrder/acq/acquisition_workers.py
> Restore previous MDA settings after acquisition

- setup.cfg
Work-around for #300.
Edit: do not close issue automatically upon merge.
> Pin NumPy version

- docs/README.md
> Link to calibration guide from index

- setup.cfg
make napari and pyqt dependencies platform specific. Fixes #193.
> Update setup.cfg for macos_arm64 specific dependencies

- recOrder/scripts/cli.py
Fixes #315.
With this PR I can run `recorder info` and `recorder convert` without a screen.
> Move imports into cli functions

- recOrder/acq/acquisition_workers.py
Fixes https://github.com/mehta-lab/recOrder/issues/338.
Tested on all combinations of [Retardance + Orientation, Phase, Retardance + Orientation + Phase] and [2D, 3D]. All of the resulting zarrs can be drag-and-drop opened in napari with the recorder reader.
> Write to single zarr store

- recOrder/io/utils.py
- recOrder/tests/cli_tests/test_cli.py
Remove remaining converter util function.
> Converter cleanup

- recOrder/acq/acquisition_workers.py
- recOrder/cli/apply_inverse_transfer_function.py
- recOrder/cli/compute_transfer_function.py
- recOrder/cli/printing.py
- recOrder/cli/settings.py
- recOrder/plugin/main_widget.py
- recOrder/tests/cli_tests/test_settings.py
Tested with `waveorder`'s `reg-params` branch.
> Connect regularization parameters

- docs/microscope-installation-guide.md
- recOrder/plugin/main_widget.py
Fixes #311 
The `.csv` is being distributed now. I tested with 2023-04-26, and everything's working well.
> Bump MM to 2023-04-26

- setup.cfg
> Bump to `iohub==0.1.0.dev5`

- recOrder/acq/acquisition_workers.py
- recOrder/calib/calibration_workers.py
This PR contains integration fixes for recOrder's GUI. 
The CLI now creates an empty zarr up front, so the GUI needed minor updates to be compatible with this working mode. 
Tested on hummingbird.
> GUI save to plate

- recOrder/cli/apply_inverse_models.py
- recOrder/cli/apply_inverse_transfer_function.py
- recOrder/cli/option_eat_all.py
- recOrder/cli/parsing.py
- recOrder/cli/printing.py
- recOrder/cli/reconstruct.py
- recOrder/cli/utils.py
- recOrder/io/core_functions.py
- recOrder/io/metadata_reader.py
- recOrder/tests/cli_tests/test_reconstruct.py
This replaces #392. 
This PR adds multiprocessing.  We can reconstruct single positions and multiprocess over the time dimension.
> Multiprocessing after 0816 refactor

- recOrder/plugin/main_widget.py
Due to unknown reasons, HCS plates or wells read by ome-zarr-py will be a nested Dask graph. These data objects remain type of `dask.array.core.Array` even after calling `compute()`, which should normally return a NumPy array. This PR calls `compute()` once before computing overlay when it detects such abnormal objects.
Fix #416.
> Simplify Dask graph before computing overlay

- docs/napari-plugin-guide.md
- recOrder/plugin/main_widget.py
> "Orientation Legend" -> "Visualization" tab

- recOrder/plugin/main_widget.py
**Before this PR:** drag-and-drop overlays would error because I was squeezing the input dimension but not the scale
**After this PR:** drag-and-drop overlays are working as expected.
> Squeeze scale with image

- recOrder/cli/settings.py
- recOrder/plugin/_widget.py
- recOrder/scripts/launch_napari.py
@naihsuanshao @ziw-liu here's a rough-and-ready version of the dynamic layout of the reconstruction wizard. 
@ziw-liu I still ended up using recursion, though in a modified form. Please suggest/make improvements. 
I used a simple counter to keep track of how many widgets to add/delete on each update. Good idea? Or naive trap?
https://github.com/mehta-lab/recOrder/assets/9554101/cd740db3-cd0a-40c9-83be-1bb48f4f9d44
> Dynamic layout of reconstruction wizard

- recOrder/cli/reconstruct.py
- recOrder/plugin/_widget.py
Uploading Screen Recording 2023-10-11 at 1.28.02 PM.mov…
The reconstruct button now mimics the CLI and shows the results in napari.
> Minimally working reconstruct button

- .github/workflows/pytests.yml
- .github/workflows/test_and_deploy.yml
- README.md
- docs/development-guide.md
- docs/microscope-installation-guide.md
- docs/software-installation-guide.md
- setup.cfg
- tox.ini
Support and test on 3.11. Also bump the suggested version in install guides to 3.10.
> Bump python versions
