README.md

1. Fixed image file link to work with PyPI using [these instructions](https://stackoverflow.com/questions/41983209/how-do-i-add-images-to-a-pypi-readme-that-works-on-github). Tested locally using [`grip`](https://github.com/joeyespo/grip) then uploaded to TestPyPI with version 0.1.0b1: https://test.pypi.org/project/recOrder-napari/0.1.0b1/. 
2. Minor installation update: use `napari -w recOrder-napari`.

Fix README for PyPI and new name.

---

.github/workflows/pytests.yml
.github/workflows/test_and_deploy.yml
.pre-commit-config.yaml
README.md
pyproject.toml
recOrder/acq/napari.yaml
recOrder/data/__init__.py
recOrder/tests/conftest.py
recOrder/tests/converter_tests/test_converter.py
recOrder/tests/pipeline_tests/test_fluorescence_deconvolution_pipeline.py
recOrder/tests/pipeline_tests/test_phase_from_bf_pipeline.py
recOrder/tests/pipeline_tests/test_qlipp_pipeline.py
recOrder/tests/pipeline_tests/test_qlipp_pipeline_tiff.py
setup.cfg
setup.py
tox.ini

**Testing**: 
- faster tests and no more repeat downloads of large fixtures for local tests
- tox installed and configured: excellent for testing in virtual environments to catch installation errors
- tox + new gh action tests installation on ubuntu, macos, and windows (several minor fixes to make sure installation passes everywhere)
- Tests now pass on python 3.7, 3.8, 3.9, 3.10.
**New GH workflow**: 
- based on the napari plugin cookiecutter, I've added a "test-and-deploy" workflow that performs a large array of tox tests when a version tag is pushed. This action can deploy to PyPI if the tests pass (via `build` and `twine`), but I've commented these out for now.
**README**: 
- basic badges added
- create an environment with `conda create -n recorder python`...no need to specify python …

Improved testing, configs, and dev tools

---

recOrder/plugin/widget/main_widget.py

Bug was in recOrder and an interaction between Qt and python.
When an "Orientation" or "Retardance" layer is deleted the "Display" combo boxes are corresponding sliders are updated so that the ranges are meaningful. When the last layer is deleted, the Qt combo box becomes empty and the Qt docs say that QComboBox.currentIndex() will return -1. We were using this index to index a numpy list which was causing the errors. 
Fix checks for index != -1 and skips the update if that's the case.

Fix warnings when all layers are deleted: issue #113

---

recOrder/plugin/widget/main_widget.py
setup.cfg

**Two changes:**
1. This addresses #115 by warning the user about MicroManager compatibility issues and explicitly recommends the 20210713 nightly build (the build we're currently using on all scopes in the lab). 
2. This downgrades and pins pycromanager to version 0.13.2, the latest version that is compatible with the MM 20210713 nightly build (ZMQ version 4.0.0). The ZMQ warnings disappear. 
Important related pycromanager discussion: https://github.com/micro-manager/pycro-manager/issues/260
Instead of the approach I'm suggesting here, @ieivanov suggested that we always pull the latest pycromanager version and manually update whichever MM install we're using by copy-pasting .jars. I tried this approach and it works, but I'm hesitant to use it because it requires managing the .jars and …

Pin pycromanager and MicroManager versions

---

recOrder/io/_reader.py
recOrder/napari.yaml
recOrder/tests/reader_tests/test_reader.py

This PR allows the user to drag and drop `ome.tif` files saved by micromanager into `recOrder`. Instead of forcing the user to convert to .zarr, this PR will allow the user to quickly check the result of a micromanager acquisition. 
After this PR is merged,`recOrder`'s napari reader will accept both `ome.tif` files and `.zarr` files. All of the readers call the corresponding `waveorder` readers. 
This PR includes tests on the multi-position file `2021_06_11_recOrder_pytest_20x_04NA/2T_3P_81Z_231Y_498X_Kazansky_2`. I have also tested with files that have a single position, a single z slice, a single channel, and a single time point. 
This reader strongly depends on the [`waveorder` reader](https://github.com/mehta-lab/waveorder/tree/master/waveorder/io), which includes [more comprehensive …

Add ome-tiff reader to `recOrder` (via `waveorder`)

---

recOrder/io/zarr_converter.py

This PR and a [parallel waveorder PR](https://github.com/mehta-lab/waveorder/pull/77) address issue #121. 
@JohannaRahm was having difficulty converting a specific `.ome.tif` file to `.zarr`, and I traced the issue to a problem with the reader for data acquired with micromanager-2.0.0-beta. The fix requires small changes to `recOrder` and `waveorder`. 
@JohannaRahm, I have successfully converted the dataset you requested and placed the result at `/hpc/projects/comp_micro/sandbox/Talon/`. @JohannaRahm can I request that you visit that location and do the following?: 
- verify that the `.zarr` has been converted appropriately for your downstream processing
- follow the detailed steps in README.txt to recreate the conversion. (Briefly, you'll create a new conda environement, checkout the …

Fix ome-tif to zarr converter for acquisitions with micromanager beta 

---

recOrder/tests/calibration_tests/test_calibration.py

Test should fail in this branch from main, and should pass when I merge into `require-importlib-metadata`.
Calibration code has no unit or integration tests, so this serves as a minimal smoke test.

Test calibration imports

---

recOrder/tests/conftest.py

@ieivanov I owe an apology for deleting these lines a few months ago without much announcement, then you were likely confused and had to reintroduce them. 
I'm suggesting deleting them again because I would like to run new/modified tests locally without waiting for the test data to download. 
I'm suggesting that we keep the test data, but you may have a better solution. Is there a reason to delete them? I don't think GitHub actions complains? Is there a different workflow that you use to quickly iterate and rerun the tests without waiting for a complete download?

Don't delete test data?

---

recOrder/scripts/cli.py
recOrder/tests/pipeline_tests/test_qlipp_pipeline.py

I accidentally introduced a regression that broke the CLI in #133 (I failed to move `import os` into the new file). 
This PR fixes the regression and adds a test that runs the CLI in a background process and checks if it finishes successfully. This type of end-to-end test will give us more confidence that the CLI can run at all. Even though we were unit testing the functions underlying the CLI calls, the CLI was unusable and this bug made it past the tests.

CLI regression fix and end-to-end CLI test

---

recOrder/tests/calibration_tests/test_calibration.py
setup.cfg

#149 was introduced by #127, and this fixes the issue. 
This error snuck by my review because I assumed `importlib_metadata` was a builtin. My bad. I'm surprised this snuck by our tests...I will look closer tomorrow morning and update the tests to catch. 
I tested a successful install by hand. Ready to merge from my perspective.

Require importlib-metadata

---

recOrder/plugin/workers/acquisition_workers.py

This PR fixes #110, and was split from #160 (started by @ieivanov). 
This change checks for equality of exposure time across channels. If the exposures are not equal it uses the exposure associated with State0 and TODO: warns the user. 
This initial implementation only applies to 3D birefringence acquisitions. TODO: the final implementation should apply to all birefringence acquisitions.

Check for equal exposures across channels

---

recOrder/io/utils.py
recOrder/pipelines/qlipp_pipeline.py
recOrder/plugin/widget/main_widget.py
recOrder/plugin/workers/acquisition_workers.py

This PR fixes background correction bugs for:
- non-square cameras --- the `load_bg` function contained a bug that caused non-square images to apply a constant background correction instead of a pixel-wise background correction. This bug affected automaton and Yuming's setup (Oryx cameras), but not hummingbird which is why this bug slipped by previous tests. 
- online mode --- online results now match offline results in 'Estimated' and 'Measured + Estimated' modes. Currently, the online and offline modes use different section of the code for background correction, and this PR brings these sections into sync. 
I tested these fixes on automaton, and I will merge after code review. 
I'll test more thoroughly on hummingbird in advance of our 0.2.0 release.

Fix background correction for non-square images and online mode

---

recOrder/io/utils.py
recOrder/pipelines/pipeline_manager.py
recOrder/plugin/workers/acquisition_workers.py

This PR prints the following message to users who request a reconstruction (via online or offline modes) when <32 GB of RAM is available:
"WARNING: recOrder reconstructions often require more than the 16 GB of RAM that this computer is equipped with. We recommend starting with reconstructions of small volumes ~1000 x 1000 x 10 and working up to larger volumes while monitoring your RAM usage with Task Manager or htop."
When >32 GB is available (e.g. 64 GB), it prints:
"64 GB of RAM is available."
I'm happy to take wording edits or completely overhaul this PR given our discussion in #108. 
Note: `psutil` is a dependency of one of our dependencies, so it is already installed in `recOrder` environments.

Print RAM warning message in online and offline modes

---

recOrder/io/utils.py
recOrder/pipelines/qlipp_pipeline.py
recOrder/plugin/widget/main_widget.py
recOrder/plugin/workers/acquisition_workers.py

When I was testing calibration using an ROI, I noticed that the background correction changed behavior. 
I found that when a calibration ROI was used, the background correction averaged over this ROI then applied that background correction uniformly over the whole image. I cannot think of a reason to average over a FOV within a background image, so I removed this functionality. 
This functionality severely reduces the effectiveness of the "Measured" background corrections when calibrating within an ROI. It's also likely that this bug was partially responsible for Yuming's poor background corrections.

Remove background averaging 

---

recOrder/io/utils.py
recOrder/pipelines/pipeline_manager.py
recOrder/plugin/workers/acquisition_workers.py

The RAM implementation in [#157](https://github.com/mehta-lab/recOrder/pull/157#discussion_r972256905) does not offer a visual hint in the GUI. The use of `print()` in the CLI also limited the way we can format the message. Here is a modified version with a more portable API.

Show RAM warning in GUI / log in CLI

---

recOrder/plugin/widget/main_widget.py

Almost every time I run a calibration I need to scroll down and click the "Plot" tab. This changes the default focus.

Set focus to "Plot" tab by default

---

recOrder/plugin/widget/main_widget.py

See screenshots of the changes below:
This PR is consistent with our goal for 0.2.0 --- all user-facing features should work well. I'm hiding these features because they are not currently working well, and we're planning to fix/improve them for 1.0.0.

Hide "listen" and "overlay" features from `recOrder` GUI

---

recOrder/io/utils.py

In #114 I've been keeping notes for how to solve mismatched background and image sizes for 1.0.0, but a clean implementation will require a refactor in waveorder. 
I tested mismatched background and image sizes, and found many cryptic error messages. To improve usability, I'm now always loading the background images (instead of preallocating the arrays and failing at load time) and warning the user if the sizes are mismatched. 
I've tested this behavior on hummingbird, and it's passed all of my checks.

Always load background and warn if background and image sizes are mismatched

---

recOrder/plugin/widget/main_widget.py

Currently, clicking `Capture Background` before loading or running a calibration gives the following error:
`Error: 'NoneType' object has no attribute 'capture_bg'`
This PR changes `recOrder`'s behavior so that the following warning is shown instead: 
```Capturing a background requires calibrated liquid crystals. Please either run a calibration or load a calibration from file.```
(Please excuse the extra commits---I'm still getting the hang of VScode :) )

`Capture Background` without calibration yields a warning

---

recOrder/io/utils.py

This PR is an improvement on #181 given a discussion @ziw-liu and I had about errors vs. warnings. 
Since `recOrder` can't recover from mismatched background and acquisition sizes, I have changed this warning to an error. This has the added benefit of making the error message appear to the user directly, instead of the old behavior where we received a downstream numpy error and a less visible warning.

Mismatched x/y size of background and acquisition should error instead of warn

---

recOrder/plugin/workers/calibration_workers.py

Previously loading calibration from a metadata file does not initialize LC values in the `QLIPP_Calibration` object created by the `load_calibration` thread worker, which [causes an error when trying to capture background afterwards](https://github.com/mehta-lab/recOrder/issues/180). This PR addresses the error by setting the required values, although the necessity of fully initializing the `QLIPP_Calibration` object when loading from metadata files is still up to debate.

Initialize calibration values when loading from metadata files

---

recOrder/io/metadata_reader.py
recOrder/plugin/workers/calibration_workers.py

This PR starts to refactor `recOrder.plugin.workers.calibration_workers` to reduce redundancy. Related: #170.
Fixes #189.

Refactor calibration workers and fix metadata writing

---

docs/development-guide.md
recOrder/calib/Calibration.py

Here's the GUI development guide, together with a small typo Rachel spotted during our session.

GUI development docs

---

recOrder/plugin/widget/main_widget.py

@ieivanov's suggested this change since the "Use Cropped ROI" checkbox mostly recreates the behavior of micromanager ROI functions.

Hide "Use Cropped ROI" checkbox

---

recOrder/calib/Calibration.py

Changing `V_min` and `V_max` to `float` as  `QLIPP_Calibration.write_metadata` fails to write json metadata if integer voltage is passed.

Fix bug in calibration_metadata writer

---

docs/microscope-installation-guide.md
recOrder/plugin/widget/main_widget.py

In #141 @ieivanov requested an slightly newer version of MM so that a [recent change to a device driver was included](https://github.com/micro-manager/mmCoreAndDevices/pull/238).
I tested `recOrder` with 2022-09-20 and all acquisition functionality is working. `pycromanager` did not require an upgrade. 
This PR updates the docs and warning messages only.

Recommend MM 2022-09-20

---

recOrder/calib/Calibration.py
recOrder/io/metadata_reader.py
recOrder/plugin/widget/main_widget.py
recOrder/plugin/workers/calibration_workers.py

Remove microscope parameters from calibration metadata

---

setup.cfg

Now `napari` installed by `pip` on Windows 10 will not run when one of some specific versions of `imageio` is fetched. This issue is somehow not causing a failure in our test-and-deploy checks.
For releasing 0.2.0 we will be matching [`napari`'s solution](https://github.com/napari/napari/pull/5168).

Block `imageio` versions that cause import error

---

.git-blame-ignore-revs

This repo squashes the commits when we merge a PR, so the `.git-blame-ignore-revs` file was ignoring a hash that no longer existed in the log. 
This PR updates now tell git blame to ignore the new squashed commit.

git blame ignore squashed commit hash

---

recOrder/tests/mmcore_tests/test_core_func.py

Our test coverage has been declining. This is an initial attempt to address this problem by using simple mock-up objects to unit-test methods that make calls to Micro-Manger APIs.
On a side note, it may be beneficial if we isolated all outbound calls via `pycromanager` and aggregate them in the `io.core_functions` module.
Starting to address #156.

Test MM Core calls with mocks

---

recOrder/calib/Calibration.py

Fixes #237 
Note that turning off autoshutter does not require an automatic shutter, i.e. this code will run even if the microscope has only a manual shutter

Turn off autoshutter before bg capture

---

.github/workflows/plugin_preview.yml
docs/development-guide.md

To address #231.
<del>
This quick attempt may not be a good long-term solution if we plan to release unstable `waveorder` to PyPI in the future. (Then we will have to pin the `waveorder` version manually before each release.)
</del>(Not an appropriate solution.)
*Update: It seems like we can just ignore the 'error' message from `pip install ./waveorder -e ".[dev]"` when we already have `recOrder` installed -- the editable installations still work.*
Alternatively, we can:
In the `[options.extras_require]` section of `setup.cfg`, add a switch for different `waveorder` versions. But this will complicate `pip isntall` on the user side. An example is how [napari handles different Qt backends](https://github.com/napari/napari/blob/c305b4607569b963ca4862172e9ef8a9715b52bc/setup.cfg#L91-L107): …

Update development guide to install `waveorder` for co-development

---

recOrder/compute/qlipp_compute.py

This PR removes a debugging print statement that was left behind, solving #258. 
@mattersoflight brought up a potential concern that "local_fit" background corrections were being applied to phase reconstructions, but I have reread the code closely and found that this is not the case. Background corrections are only being applied to polarization acquisition.

Remove background debugging print statement

---

recOrder/plugin/main_widget.py

Move the most recent layer to the top of the layers list

---

recOrder/acq/acquisition_workers.py

Fixes #265. 
Before this PR, if you clicked "Retardance + Orientation + Phase" in 2D mode, `recOrder` would acquire a 3D stack and only use the central slice to recover retardance and orientation. After this PR, `recOrder` will average over Z (in the background-corrected Stokes parameters) before reconstructing the retardance and orientation. 
This feature can be valuable for averaging over noise or small structures, but it also averages over the blurry defocus images which can reduce contrast in the final result. The old behavior---reconstructing retardance and orientation from a single slice---is still available to the user via the "Retardance + Orientation" button in 2D mode. 
The attached figure summarizes the fix. Note: the left and right columns use identical contrast limits.

"Retardance + Orientation + Phase" in 2D mode averages over z for retardance and orientation instead of slicing

---

examples/3D-bf-to-2D-phase.py
examples/3D-bf-to-3D-phase.py
examples/README.md
examples/recon-qlipp.py
recOrder/compute/qlipp_compute.py

This PR 
- adds a new `example/3D-bf-to-2D-phase.py` script
- adds a new `in_focus_slice` argument to allow this scripts to easily specify an in-focus slice
- adds a `README` to the example scripts with pointers on how to use and develop them

Add 3D->2D phase script and add `in_focus_slice` argument

---

recOrder/compute/qlipp_compute.py

This PR throws a `ValueError` if the user requests a reconstruction with the illumination or detection NA are greater than the index of refraction of the media: these correspond to non-physical parameters. 
If the user uses, for example, NA_obj = 1.1 and n_obj_media = 1.0, the user would see:
Before this PR:
`RuntimeWarning: invalid value encountered in sqrt
oblique_factor = ((1 - lambda_in**2 * fr**2) *Pupil_support)**(1/2) / lambda_in`
along with a `nan` reconstruction. 
After this PR:
`ValueError: Parameters are non-physical: NA_obj > n_obj_media` with no reconstruction.

Check for non-physical NA arguments

---

docs/microscope-installation-guide.md
recOrder/plugin/main_widget.py

Before this PR, the "BF Channel" list would be populated with all MM presets, which would lead to confusing defaults like this:
After this PR, the "BF Channel" list will only contain MM presets that have any of the following case-insensitive keywords as a substring:
`["bf", "brightfield", "bright", "labelfree", "label-free", "lf", "label"]`
I checked these keywords against the latest MM configs on `CompMicro_MMConfigs` and tested in person on hummingbird and falcon. Feel free to suggest/add other keywords.
On hummingbird, the startup menus now look like this (similar on falcon):

Populate "BF Channel" list with presets containing keywords

---

recOrder/acq/acquisition_workers.py
recOrder/calib/calibration_workers.py
recOrder/plugin/main_widget.py

Save GUI state with snapped images

---

recOrder/acq/acquisition_workers.py

In #160 I changed the polarization acquisition buttons to keep the shutter open between channels and slices, but I failed to do the same for "2D phase acquisitions" (which actually acquires a 3D stack and reconstructs the 2D phase). This one-line PR makes the shutter behavior consistent and keeps the shutter open during 2D phase acquisitions.

Keep shutter open during 2D phase acquisitions

---

recOrder/plugin/main_widget.py

Fixes #293. 
When no brightfield preset is found in the MM config, `recOrder` will:
**Before this PR:** show a complete list of presets available and let the user acquire a brightfield stack from any of those presets. 
**After this PR:** disable the "Phase From BF" button, disable the "BF Channel" dropdown box (now empty). If the user mouses over either the disabled button or the disabled dropdown, the tooltip in the following screenshot will appear. 
Note: the user can acquire "Retardance + Orientation" or "Retardance + Orientation + Phase" when no brightfield preset is found because those acquisitions do not require a brightfield channel. 
Edit: extra comma between "the" and "following" in screenshot above removed

Disable "Phase From BF" button when no BF channel is found - add tooltip

---

recOrder/compute/reconstructions.py

Fixes [waveorder #102](https://github.com/mehta-lab/waveorder/issues/102).
**TL;DR: transposes and copies are slowing down the `recOrder`->`waveorder` inferface**
The `recOrder` -> `waveorder` adapter functions use transposes to bridge the gap between `recOrder`'s CZYX order and `waveorder`s CXYZ order. Transposes of >=3-dimensional arrays can result in non-contiguous views of the original arrays, and the copied versions also inhabit non-contiguous regions of memory. This means that `waveorder` is often receiving non-contiguous arrays. 
`numpy` functions give the correct answers when you pass non-contiguous arrays, but the results are often much slower. Fancy indexing, and `.copy` operations are particularly slow when they operate on non-contiguous arrays since they need to seek across a …

Transpose + np.copy() + (fancy indexing and/or  `ndarray.copy()`) causes major slowdowns

---

.gitignore
examples/README.md
examples/parallel-reconstruct.py

Fixes #299.
This example script downloads the recOrder test dataset (if it hasn't already been downloaded), converts the MM dataset to zarr, then uses multiprocessing to read and write each position and time point into a new zarr store in parallel. 
I have confirmed a ~5.5-fold speedup processing this 6-volume (T=2, P=3) test dataset on the HPC login node. I was not able to get the same speedup on my local machine (weird macOS behavior with core handling?). 
Thanks @ziw-liu and @edyoshikun for your suggestions. I found that converting to zarr helped (as expected), and I found that using the HPC was essential...multiprocessing isn't working well locally.
@ziw-liu I'm happy to take suggestions for cleaning up this script. I'm still not sure how we can best deploy multiprocessing and slurm …

Multiprocessing script for reconstructing multiple positions and times

---

setup.cfg

While testing I temporarily depended on a specific `iohub` commit instead of a tagged version. I just tagged the head of `iohub` and this PR makes `recOrder` depend on that tag. 
After this merges I'll tag `recOrder` with `0.3.0rc1`.

Depend on iohub tagged release

---

recOrder/plugin/main_widget.py

Fixes #280 
Tested on hummingbird

Turn live mode off when loading calibration

---

README.md

Similar to `https://github.com/mehta-lab/waveorder/pull/116`, two of the links on PyPI are broken. This PR pins the links. I think this issue is minor enough that is doesn't justify a rerelease, but I'm fixing this now so that we don't forget for the next release.

Pin README links

---

README.md
recOrder/acq/acquisition_workers.py
recOrder/cli/apply_inverse_transfer_function.py
recOrder/cli/compute_transfer_function.py
recOrder/cli/main.py
recOrder/cli/parsing.py
recOrder/cli/printing.py
recOrder/cli/reconstruct.py
recOrder/cli/settings.py
recOrder/cli/view.py
recOrder/io/utils.py
recOrder/tests/cli_tests/test_cli.py
recOrder/tests/cli_tests/test_settings.py
setup.cfg

@ziw-liu @mattersoflight I can demo my progress tomorrow to help us put together a plan. 
I've tested this branch against `waveorder`'s `pol-refactor` branch. 
Confirmed working:
- torch installation on hummingbird 
- new CLI `calculate-transfer-function` and `apply-inverse-transfer-function` can perform all reconstruction steps
- GUI buttons are connected to the new CLI: all 3 acquisition buttons (in both 2D and 3D modes) return results to the screen. Out-of-the-box polarization acquisitions look good. The GUI calls the CLI functions and spits out commands to recreate the transfer functions and reconstructions...initial tests look good.
Major limitations to address:
Minor limitations:
- docs, CLI automated testing, much more! 
- `apply_inverse_transfer_function` is where most of the …

`recOrder` buttons working via CLI 

---

recOrder/acq/acquisition_workers.py
recOrder/cli/apply_inverse_transfer_function.py
recOrder/cli/settings.py
recOrder/plugin/main_widget.py

Fixes #349. 
@edyoshikun I couldn't get `DirectoryPath` to work in the way you suggested, but I ended up finding a fairly simple method with `os.path.isdir`. 
I've tested on hummingbird.

Connect background corrections

---

docs/microscope-installation-guide.md
recOrder/calib/Calibration.py
recOrder/plugin/main_widget.py

This PR upgrades `recOrder` to depend on MM nightly build `2023-04-18`. 
I have tested this branch on automaton in all three calibration modes. 
Upgrading an existing `recOrder-napari==0.3.0` is fairly involved---budget at least 60 minutes. The simplest steps we've found are:
- uninstall CellDrive5000, the associated USB drivers, and "National Instruments Software"
- use the Meadowlark-distributed USB drive to reinstall CellDrive5000 and USB drivers with the upgraded versions. (@ieivanov should we distribute this software to upgrading users by hand? - I think our only upgrading users are us and the Elicieri lab?)
- upgrade your configuration file (the device name has changed)
This fixes most of #311, but I am not closing it because we are still distributing one device driver and the …

Depend on MM 2023-04-18

---

recOrder/io/utils.py
recOrder/plugin/main_widget.py
recOrder/tests/util_tests/test_overlays.py
setup.cfg

Fix #348.
Currently this does not delay the compute and brings all the data into memory. So it will NOT work with large datasets.
Making it work lazily through Dask needs some changes to the overlay rendering function, which uses `np.copy()` that is not supported by Dask arrays.

Draw birefringence overlay on napari layers event

---

setup.cfg

- @ieivanov requested that we bump recOrder's pycromanager dependency to support some of the features that mantis needs. 
- I tested 0.25.40 (matching mantis' depenedency), and found that it had issues with multithreading: see https://github.com/micro-manager/pycro-manager/issues/555 and fix https://github.com/micro-manager/pycro-manager/pull/558
- I tested the pycromanager release 0.27.2 (the release before our current MM release 2023-04-26), and found it's working well. 
- I tested the latest pycromanager release 0.27.5, and found that the ZMQ version has been bumped, so we'll need to upgrade it at the same time as MM. This can happen later.

Upgrade pycromanager to 0.27.2

---

.github/workflows/pytests.yml
.github/workflows/test_and_deploy.yml
recOrder/acq/acquisition_workers.py
recOrder/calib/calibration_workers.py
recOrder/plugin/main_widget.py
recOrder/tests/widget_tests/test_dock_widget.py
setup.cfg
tox.ini

Checks that the GUI can be initialized and docked to the napari viewer without throwing an error.

Test docking the plugin widget

---

recOrder/plugin/main_widget.py
recOrder/tests/util_tests/test_overlays.py

Implements https://github.com/mehta-lab/recOrder/pull/357#issuecomment-1526522379.
This works on a best-effort basis. If the user deletes part of the layer list (e.g. keeping orientation but not retardance) and loads another dataset, this will produce wrong overlays.
Also this treats any layer whose name ***starts with*** 'Retardance' and 'Orientation' as a birefringence layer. So layers with names like 'Retardance-mask' and 'Orientation of the fish body axis' will also be treated as birefringence layers and cause errors.

Multiple birefringence overlays

---

.github/workflows/test_and_deploy.yml

**Before:** Tests run only on PRs to `main`
**After:** Tests run on all PRs 
**Symptom:** In #381 I used some local spot tests, then saw the checkmarks on GH actions and thought everything was working well. On merging #381 into `0.4.0dev`, I found that the tests weren't actually running...the checkmark was only for napari hub checks. Not a big deal; I  will fix the tests in `0.4.0dev`.

Run CI/CD tests on all PRs

---

recOrder/calib/Calibration.py
recOrder/io/utils.py

Fix #213.
Also remove the orphaned `get_unimodal_threshold` function. This was likely used for segmentation (e.g. finding nuclei mask) and is now part of other analysis pipelines. We can also add a deprecation warning instead of removal for 0.4.0 if anyone is potentially still using it from here.

Remove assertion and unused function

---

.github/workflows/test_and_deploy.yml
recOrder/cli/apply_inverse_transfer_function.py
recOrder/cli/compute_transfer_function.py
recOrder/cli/reconstruct.py
recOrder/tests/cli_tests/test_compute_tf.py
recOrder/tests/cli_tests/test_reconstruct.py
recOrder/tests/cli_tests/test_settings.py
recOrder/tests/conftest.py
setup.cfg

This PR against `0.4.0dev` includes the test fixes that should have appeared in #381 (see #383 for CI/CD fix).

Fix 0.4.0dev tests

---

recOrder/tests/widget_tests/test_dock_widget.py
setup.cfg

- With napari 4.18, Qt6 is now an explicit option, so we can remove the workaround added for #193.
- Bumping iohub to v0.1.0dev4
- With the Qt change, the dock widget test is now passing on Linux CI runners too.

Bump dependencies and enable widget test

---

docs/meadowlark-software-upgrade.md
docs/microscope-installation-guide.md

This PR implements some of the decisions we made in #382. 
Note that this PR is against `patch/0.3.x`. See #304 for context about keeping maintenance branches. 
After this PR:
- the 0.3.1 documentation will include a compatibility table
- the 0.3.1 documentation will be synchronized with the 0.4.0 documentation in #395 
After this PR merges I will release 0.3.1 and push to PyPI.

0.3.1 documentation patch

---

docs/development-guide.md
docs/meadowlark-software-upgrade.md
docs/microscope-installation-guide.md

Together with #394, fixes #362. 
Replaces #382. 
After this PR the documentation:
- includes a compatibility table
- recommends that the user download the USB driver from a direct link to our github release page. [I've made a test pre-release for this purpose.](https://github.com/mehta-lab/recOrder/releases/tag/0.4.0rc0)
- is synchronized with the documentation in #394, which will appear with the 0.3.1 release

0.4.0 installation documentation

---

examples/birefringence-and-phase.yml
examples/birefringence.yml
examples/fluorescence.yml
examples/phase.yml
recOrder/cli/apply_inverse_transfer_function.py
recOrder/cli/settings.py
recOrder/tests/cli_tests/test_reconstruct.py

`recorder reconstruct` naively loops through all time points, applying the reconstruction as it goes. This default is limiting for datasets with a large number of time points where it is more convenient to reconstruct a single time point on a single core (via multiprocessing or slurm). 
This PR adds a configuration-file option `time_indices` with signature:
`time_indices: Union[NonNegativeInt, List[NonNegativeInt], Literal["all"]] = "all"`
By default `time_indices: "all"` reconstructs all time point, which is backwards compatible. 
If `time_indices: 5`, then only time-point 5 will be reconstructed.
Finally, if
```
time_indices:
- 0 
- 5
- 10
```
then the 0th, 5th, and 10th indices will be reconstructed. 
@edyoshikun requested this feature for simplifying parallel reconstructions with …

Reconstruct a subset of time indices

---

recOrder/cli/apply_inverse_transfer_function.py
recOrder/tests/cli_tests/test_reconstruct.py

Pass scale metadata through `recorder reconstruct`

---

recOrder/plugin/main_widget.py

Fixes #403.
In [PyQt5, `QFileDialog` has a class called `Options` that stores existing options.](https://www.riverbankcomputing.com/static/Docs/PyQt5/api/qtwidgets/qfiledialog.html#qfiledialog) 
In [PyQt6, this class seems to have disappeared](https://www.riverbankcomputing.com/static/Docs/PyQt6/api/qtwidgets/qfiledialog.html#qfiledialog), although `QFileDialog.Options()` calls still appear further down the docs page (?).
This two-line fix seems to have fixed the issue on hummingbird, where I tested the "Browse" buttons and "Load calibration".  
We don't set options anywhere else, so I don't expect any changes to the previous behavior.

Skip `QFileDialog.Options()`

---

docs/reconstruction-guide.md
recOrder/acq/acquisition_workers.py
recOrder/calib/calibration_workers.py
recOrder/cli/apply_inverse_transfer_function.py
recOrder/cli/compute_transfer_function.py
recOrder/cli/main.py
recOrder/cli/option_eat_all.py
recOrder/cli/parsing.py
recOrder/cli/reconstruct.py
recOrder/cli/utils.py
recOrder/io/utils.py
recOrder/tests/cli_tests/test_compute_tf.py
recOrder/tests/cli_tests/test_reconstruct.py
recOrder/tests/conftest.py

This PR changes recOrder's CLI signatures to:
```
recorder reconstruct `
-i ./data.zarr/*/*/* `
-c ./config.yml `
-o ./reconstruction.zarr
recorder compute-tf `
-i ./data.zarr/0/0/0 `
-c ./config.yml `
-o ./tf.zarr
recorder apply-inv-tf 
-i ./data.zarr/*/*/* `
-t ./tf.zarr `
-c ./config.yml `
-o ./reconstruction.zarr
```
This PR is an important step towards solving #396, so I'm tagging @edyoshikun. 
These standards match the recent changes to the mantis repo. There is some duplication in the `parsing.py`, `utils.py`, and `option_eat_all.py` files between `recOrder` and `mantis`, but after the next recOrder release we'll delete the duplication from the mantis repo.
This PR potentially affects the GUI, so I did a quick test on hummingbird to confirm all reconstructions still run.

Standardize CLI

---

recOrder/acq/acquisition_workers.py
recOrder/calib/calibration_workers.py
recOrder/cli/apply_inverse_transfer_function.py
recOrder/cli/reconstruct.py
recOrder/cli/utils.py
recOrder/tests/util_tests/test_create_empty.py

Fixes #407, and makes progress towards #396. 
This PR refactors `apply_inverse_transfer_function` so that a complete HCS plate is created in advance then filled. 
@edyoshikun I've changed (and hopefully simplified) some of the logic you were using on the mantis side...see `apply_inverse_transfer_function.py L405-L425`. I'm getting all of the reconstruction-specific metadata, using it to create an empty HCS zarr, then looping through the input positions, inverting and writing as I go. 
I expect/hope that reconstruction-specific metadata can be swapped for deskew-specific or other metadata, and that this pattern is compatible with multiprocessing.

CLI creates empty HCS zarr then fills it

---

recOrder/__init__.py

Fixes #409.
I tried checking imports like @ziw-liu suggesting, but after `pip uninstall PyQt5` I was still able to `import PyQt5`. The environment variable also failed. 
I tested this solution on hummingbird.

Check for PyQt5

---

docs/README.md
docs/data-schema.md

Fixes #371 
This PR describes `recOrder`'s current storage schema for discussion. Let's iterate on the schema here, then after this merges I will modify `recOrder` to match the schema. 
Here's a list of the issues I think should be addressed together with my suggestions:
- **consistent numbering:** I'll vote for the first `BG` to be `BG_0` to match the snaps
- **consistent case:** I'll vote for snake_case everywhere, so `BG` -> `bg`, `recOrderPluginSnap` -> `recorder_plugin_snap` and `<acq_name_0>_RawPolDataSnap.zarr` -> `<acq_name_0>_data.zarr`
- **simpler names:** I'll vote for `<acq_name_0>_recOrderPluginSnap` -> `<acq_name_0>_snap`, and `<acq_name_0>_RawPolDataSnap.zarr` -> `<acq_name_0>_raw_data.zarr`
- **consistent path to raw data**: we currently save polarization data to …

`recOrder` data schema

---

recOrder/plugin/main_widget.py

Fixes #406.
This PR puts a newly generated birefringence overlay as the top layer (for new acquisitions and dragged-in zarr stores). 
The previous logic would only update the birefringence overlay if it did not already exist. This failed to trigger during repeat `recOrder` acquisitions, which write to the birefringence overlay in place so it always exists. 
The new logic only updates the birefringence overlay when the last layer starts with "Orientation", which always follows "Retardance" in the layer order. This logic prevents "mixed updating" bugs where the overlay generation happens with the orientation from one dataset and the retardance from the previous dataset. 
Tested on hummingbird.

Birefringence overlays on top

---

recOrder/calib/Calibration.py
recOrder/plugin/main_widget.py

This PR makes several QOL improvements to the backgrounds in recOrder:
- correctly passes the scale to the backgrounds (missed in my fixes for #426). Background acquisitions use repeated snaps, so I needed to pass the scale "manually"
- renames the background layers for compatibility with the new overlay generator
- squeezes the arrays before adding them to layers. This fixes a confusing behavior where the background would show raw data with a slider, then subsequent acquisitions would only show a retardance+orientation acquisition when the slider was at position 0.

Background scaling, naming, and squeezing

---

README.md
docs/microscope-installation-guide.md
docs/reconstruction-guide.md
setup.cfg

This PR contains minor fixes to prepare for the 0.4.0 release:
- Fixes #432. Documents the relationship to waveorder and iohub, and adds `iohub convert` instructions
- Depend on `wget` - because the sample contributions require it
- Updates the version number in the docs

0.4.0 release fixes

---

README.md

Here is the `0.4.1rc0` release page: https://pypi.org/project/recOrder-napari/0.4.1rc0/
I don't expect the videos to appear on PyPI since they're hosted on github (the links will download them correctly). 
This PR is an attempt to get the youtube thumbnail to appear correctly on the PyPI release page.

Direct link to README image

---

examples/birefringence-and-phase.yml
examples/birefringence.yml
examples/fluorescence.yml
examples/phase.yml
recOrder/cli/apply_inverse_transfer_function.py
recOrder/cli/compute_transfer_function.py
recOrder/cli/settings.py
recOrder/plugin/_widget.py
recOrder/tests/cli_tests/test_compute_tf.py
recOrder/tests/cli_tests/test_reconstruct.py
recOrder/tests/cli_tests/test_settings.py
recOrder/tests/conftest.py
recOrder/tests/util_tests/test_io.py

This PR revises the pydantic settings model for compatibility with magic-gui, then updates the dependent reconstruction code and tests (which are now passing). 
See `/examples/` for the new settings layouts---only minor changes to the way that "Phase", "Birefringence", etc. modes are handled.

Revise settings for magic-gui compatibility

---

recOrder/cli/compute_transfer_function.py
recOrder/tests/cli_tests/test_compute_tf.py

Fixes #460. Supersedes #461. Tested on @dsundarraman's reconstructions. 
This PR chunks the transfer functions along YX, matching the reconstruction chunking. 
**Details:** Writing to a .zarr with `__setitem__` (i.e. `dataset['group_name'] = myarray`) uses a single chunk, so requesting a large reconstruction failed when the chunk exceeded 2147483647 bytes. The fix is to use `create_image` instead of `__setitem__` so that we can set the chunk size.
**Notes on tests:** my first commit was a test on a large transfer function that failed locally, and my second commit fixed the problem and made the test pass locally. Unfortunately, the github action fails on this test, likely because it uses too much memory(?). My third commit reverts the test.

Chunk transfer functions

---

recOrder/cli/apply_inverse_transfer_function.py
recOrder/cli/utils.py
recOrder/tests/util_tests/test_create_empty.py

**Before:** `recorder reconstruct` does not pass any plate-level metadata because it takes single position as input. This was very inconvenient for @dsundarraman's work, where we need to reconstruct each FOV then use the plate-level stage-position metatdata for a first pass at stitching the FOVs. 
**After:** `recorder reconstruct` checks to see if the position is a part of a plate, and passes the plate-level metadata if is.  
---
@dsundarraman, this PR will let you run reconstructions, then merge the reconstructions directly. Here's a snippet to get you started...I expect these to be some of the first lines in `zebrapro stitch`:
```
plate = open_ome_zarr("./reconstruction.zarr")
positions = plate.zattrs["Summary"]["StagePositions"]
zyx_stage_position_list = …
```

Pass metadata

---

setup.cfg

Related https://github.com/ome/napari-ome-zarr/issues/111.
The latest versions of ome-zarr do not allow the napari plugin to read the channel names correctly. `recOrder` needs the channel names to generate birefringence overlays, so I'm pinning to an old version until this is fixed.

Pin ome-zarr

---

recOrder/io/utils.py
recOrder/io/visualization.py
setup.cfg

We typically expect HSV colormaps, so I'm changing the `ret_ori_overlay` function's default.
@edyoshikun related to: https://github.com/czbiohub-sf/shrimPy/pull/141

Default HSV colormap

---

.github/workflows/pytests.yml
.github/workflows/test_and_deploy.yml
recOrder/cli/apply_inverse_models.py
recOrder/cli/settings.py
recOrder/tests/cli_tests/test_settings.py
setup.cfg
tox.ini

Bump Python, iohub, and waveorder

---

recOrder/tests/util_tests/test_create_empty.py

Fixes #494. 
Keeps temporary data in `tmp_path`, which gets deleted.

Fix local tests 
